"""
Configuration Manager - Handles environment variables and model settings
"""

import os
import json
from typing import Dict, Any, List, Optional
from pathlib import Path


class ConfigManager:
    """Manages configuration for research tasks"""
    
    def __init__(self):
        self.env_file = Path('.env')
        self.default_config = self._get_default_config()
    
    def _get_default_config(self) -> Dict[str, Any]:
        """Get default configuration values"""
        return {
            # Model settings
            'model': 'qwen-plus',
            'temperature': 0.6,
            'top_p': 0.95,
            'presence_penalty': 1.1,
            'max_input_tokens': 320000,
            'max_retries': 10,
            
            # Execution settings
            'max_workers': 20,
            'rollout_count': 3,
            'timeout': 300,
            
            # API settings
            'serper_key_id': '',
            'jina_api_keys': '',
            'api_key': '',
            'api_base': '',
            'dashscope_api_key': '',
            'sandbox_fusion_endpoint': '',
            
            # Advanced settings
            'enable_search': True,
            'enable_visit': True,
            'enable_scholar': True,
            'enable_file_parser': True,
            'enable_python': True,
        }
    
    def load_env_config(self) -> Dict[str, str]:
        """Load configuration from environment variables"""
        env_config = {}
        
        # Check if .env file exists and load it
        if self.env_file.exists():
            try:
                with open(self.env_file, 'r') as f:
                    for line in f:
                        line = line.strip()
                        if line and not line.startswith('#') and '=' in line:
                            key, value = line.split('=', 1)
                            env_config[key.strip()] = value.strip()
            except Exception as e:
                print(f"Error reading .env file: {e}")
        
        # Also check actual environment variables
        env_vars = [
            'SERPER_KEY_ID', 'JINA_API_KEYS', 'API_KEY', 'API_BASE',
            'DASHSCOPE_API_KEY', 'SANDBOX_FUSION_ENDPOINT', 'MODEL_PATH',
            'TEMPERATURE', 'TOP_P', 'PRESENCE_PENALTY', 'MAX_WORKERS'
        ]
        
        for var in env_vars:
            if var in os.environ:
                env_config[var.lower()] = os.environ[var]
        
        return env_config
    
    def save_env_config(self, config: Dict[str, str]):
        """Save configuration to .env file"""
        try:
            with open(self.env_file, 'w') as f:
                f.write("# DeepResearch WebUI Configuration\n")
                f.write("# Generated by WebUI\n\n")
                
                for key, value in config.items():
                    if value:  # Only write non-empty values
                        f.write(f"{key.upper()}={value}\n")
        except Exception as e:
            print(f"Error saving .env file: {e}")
    
    def get_model_options(self) -> List[str]:
        """Get available model options"""
        return [
            'qwen-plus',
            'qwen-max',
            'qwen-turbo',
            'gpt-4o',
            'gpt-4-turbo',
            'claude-3-sonnet',
            'claude-3-opus'
        ]
    
    def validate_config(self, config: Dict[str, Any]) -> List[str]:
        """Validate configuration and return list of errors"""
        errors = []
        
        # Check required API keys
        if not config.get('serper_key_id'):
            errors.append("Serper API key is required for web search")
        
        if not config.get('dashscope_api_key') and not config.get('api_key'):
            errors.append("Either DashScope API key or OpenAI API key is required")
        
        # Validate numeric values
        try:
            temp = float(config.get('temperature', 0.6))
            if not 0 <= temp <= 2:
                errors.append("Temperature must be between 0 and 2")
        except (ValueError, TypeError):
            errors.append("Temperature must be a valid number")
        
        try:
            top_p = float(config.get('top_p', 0.95))
            if not 0 <= top_p <= 1:
                errors.append("Top-p must be between 0 and 1")
        except (ValueError, TypeError):
            errors.append("Top-p must be a valid number")
        
        try:
            max_workers = int(config.get('max_workers', 20))
            if max_workers < 1:
                errors.append("Max workers must be at least 1")
        except (ValueError, TypeError):
            errors.append("Max workers must be a valid integer")
        
        return errors
    
    def get_tool_descriptions(self) -> Dict[str, str]:
        """Get descriptions for available tools"""
        return {
            'search': 'Web search using Serper API - Find current information online',
            'visit': 'Visit and analyze web pages using Jina API - Read and extract content from URLs',
            'scholar': 'Search academic papers using Google Scholar - Find research papers and citations',
            'file_parser': 'Parse various file formats (PDF, Word, Excel, etc.) - Extract text from documents',
            'python': 'Execute Python code in sandboxed environment - Perform calculations and data analysis'
        }
    
    def create_task_config(self, ui_config: Dict[str, Any], questions: List[Dict[str, str]]) -> Dict[str, Any]:
        """Create a complete task configuration from UI inputs"""
        config = self.default_config.copy()
        config.update(ui_config)
        config['questions'] = questions
        
        # Set environment variables for the task
        env_config = self.load_env_config()
        for key, value in env_config.items():
            os.environ[key.upper()] = str(value)
        
        return config
    
    def get_sample_questions(self) -> List[Dict[str, str]]:
        """Get sample questions for demonstration"""
        return [
            {
                'question': 'What are the latest developments in artificial intelligence in 2024?',
                'answer': ''
            },
            {
                'question': 'How do large language models like GPT-4 work?',
                'answer': ''
            },
            {
                'question': 'What is the current state of quantum computing research?',
                'answer': ''
            }
        ]